### PR TITLE
Build arm docker image

### PR DESCRIPTION
**Pull request by dbkr**
In theory (untested)

### CODE REVIEW

**Comment by michaelkaye** [comment]
This should have built an image https://github.com/matrix-org/trafficlight/pkgs/container/trafficlight tagged pr-84

I assume you're after an arm image for A Reason - can @dbkr pull the image we built from ghcr.io and check that it does what you need?

**Comment by dbkr** [comment]
Yep, I was trying to get this to work on my laptop so having arm images avoids having to run under emulation. I'll try, but right now ghcr is just giving me 'denied'.

**Comment by dbkr** [comment]
Never mind, I must have had an expired access token for ghcr or something. I haven't yet worked out how to run trafficlight: it doesn't look like it's working but it does the same as the main image:

```
% docker run --rm -it ghcr.io/matrix-org/trafficlight:pr-84 
Traceback (most recent call last):
  File "/usr/local/bin/hypercorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hypercorn/__main__.py", line 287, in main
    run(config)
  File "/usr/local/lib/python3.11/site-packages/hypercorn/run.py", line 41, in run
    load_application(config.application_path, config.wsgi_max_body_size)
  File "/usr/local/lib/python3.11/site-packages/hypercorn/utils.py", line 122, in load_application
    app = eval(app_name, vars(module))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/app/trafficlight/__init__.py", line 68, in create_app
    app.config.from_file("trafficlight.json", json.load)
  File "/usr/local/lib/python3.11/site-packages/quart/config.py", line 269, in from_file
    with open(file_path) as file_:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/app/instance/trafficlight.json'
```

**Review by michaelkaye — APPROVED** [review]
Lets roll

**Pull request merged**
